## NumPy

In [2]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
type(matrix[0][0])

numpy.int64

In [16]:
ndarray = np.array([1, 2, 3], dtype=np.uint8)

In [18]:
ndarray.astype(np.float64)

array([1., 2., 3.])

## ndarrayの演算

In [27]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [24]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
array1

array([[1, 2, 3]])

In [29]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Shape

In [39]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [32]:
array1

array([[1, 2, 3]])

In [33]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [41]:
ndarray = np.array([[1, 2],[3, 4], [5, 6]])
ndarray.shape

(3, 2)

In [42]:
ndarray.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
array1 = np.array([1, 2, 3])

In [49]:
np.expand_dims(array1, axis=0)

array([[1, 2, 3]])

## Indexing Slicing

In [3]:
ndarray = np.array([1, 2, 3, 4])

In [5]:
ndarray[-1]

4

In [6]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])

In [8]:
ndarray[0, 1]

2

In [9]:
ndarray = np.array([1, 2, 3, 4])

In [10]:
ndarray

array([1, 2, 3, 4])

In [11]:
ndarray[1:3]

array([2, 3])

In [12]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

In [15]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

## np.arange(), np.linspace(), np.logspace()

In [17]:
np.arange(3, 15, 2)

array([ 3,  5,  7,  9, 11, 13])

In [19]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

## np.zeros(shape)

In [23]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## np.ones()

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## np.eye()

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])