## NumPy

In [2]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
type(matrix[0][0])

numpy.int64

In [16]:
ndarray = np.array([1, 2, 3], dtype=np.uint8)

In [18]:
ndarray.astype(np.float64)

array([1., 2., 3.])

## ndarrayの演算

In [27]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [24]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
array1

array([[1, 2, 3]])

In [29]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Shape

In [39]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [32]:
array1

array([[1, 2, 3]])

In [33]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [41]:
ndarray = np.array([[1, 2],[3, 4], [5, 6]])
ndarray.shape

(3, 2)

In [42]:
ndarray.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
array1 = np.array([1, 2, 3])

In [49]:
np.expand_dims(array1, axis=0)

array([[1, 2, 3]])