## NumPy

In [2]:
import numpy as np

In [3]:
np.__file__

'/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [9]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
type(matrix[0][0])

numpy.int64

In [16]:
ndarray = np.array([1, 2, 3], dtype=np.uint8)

In [18]:
ndarray.astype(np.float64)

array([1., 2., 3.])

## ndarrayの演算

In [27]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array3 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])

In [24]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
array1

array([[1, 2, 3]])

In [29]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array3

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## Shape

In [39]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [32]:
array1

array([[1, 2, 3]])

In [33]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [41]:
ndarray = np.array([[1, 2],[3, 4], [5, 6]])
ndarray.shape

(3, 2)

In [42]:
ndarray.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
array1 = np.array([1, 2, 3])

In [49]:
np.expand_dims(array1, axis=0)

array([[1, 2, 3]])

## np.randomを使って乱数生成

In [44]:
np.random.rand(3, 4)

array([[0.32151654, 0.31412053, 0.25541652, 0.16486848],
       [0.11557269, 0.20308162, 0.80396119, 0.86309252],
       [0.94917339, 0.70222378, 0.59737397, 0.25765188]])

In [53]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [60]:
np.random.randn()

-0.5281717522634557

In [61]:
np.random.normal()

-1.0729686221561705

In [64]:
np.random.randint(10, 100, (2 ,3))

array([[16, 35, 60],
       [30, 28, 94]])

In [67]:
a = [1, 2, 3]
np.random.choice(a)

1

In [69]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [70]:
np.random.choice(index_pool)

4

##　統計量を求める

In [74]:
std_norm = np.random.randn(5, 5)
std_norm

array([[ 3.80610804e-01, -7.47766359e-01, -1.31767750e+00,
         1.33291008e+00, -6.84540250e-01],
       [ 1.25598233e+00,  4.96726354e-01,  3.29275803e-01,
        -1.18990846e-03, -3.07292625e-01],
       [-1.83536999e-01, -5.52975151e-01, -1.55712804e-01,
         5.72392274e-01,  7.59955476e-01],
       [ 7.35681993e-01,  1.01389243e+00, -7.38431181e-01,
         2.57706672e-01, -1.13745173e+00],
       [ 1.57814135e+00, -1.75110568e-01, -1.72908882e+00,
        -2.44074475e-01,  1.93079609e-01]])

In [75]:
std_norm.max()

1.5781413451795898

In [77]:
std_norm.min()

-1.7290888221556728

In [78]:
std_norm.argmax()

20

In [79]:
std_norm.flatten()[20]

1.5781413451795898

In [87]:
import time
a = np.random.randn(1000, 1000)
before = time.time()
np.median(a)
after_median = time.time()
np.mean(a)
after_mean = time.time()
print('median took {} sec'.format(after_median - before))
print('mean took {} sec'.format(after_mean - after_median))


median took 0.012167692184448242 sec
mean took 0.00027108192443847656 sec


In [89]:
std_norm.max(axis=1)

array([1.33291008, 1.25598233, 0.75995548, 1.01389243, 1.57814135])

## 数学で使う便利変数

In [90]:
np.sqrt([1, 2, 3,4 ])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [95]:
x = np.linspace(1, 10 , 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [98]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [99]:
np.e

2.718281828459045

In [102]:
array = np.arange(1, 11)
np.sum([1, 2, 3])

6

In [105]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [106]:
np.sum(ndarray, axis=1)

array([15, 40])

In [107]:
array = np.arange(-10, 0)

In [109]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## np.nanとnp.isnan()

In [110]:
np.log(-100)

/tmp/ipykernel_25/60392587.py:1: RuntimeWarning: invalid value encountered in log
  np.log(-100)


nan

In [112]:
type(np.nan)

float

In [113]:
a = None
a is None

True

In [114]:
np.isnan(np.log(-100))

/tmp/ipykernel_25/473003783.py:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(-100))


True

## そのほか便利関数

In [115]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
np.clip(array, 3 , 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [120]:
1e-4

0.0001

In [121]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [124]:
np.where(array > 3)

(array([4, 5, 6, 7, 8, 9]),)

In [125]:
array > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [129]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [130]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [132]:
(ndarray > 3).any()

True

In [134]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [136]:
np.unique(array, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [137]:
np.bincount(array)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## np.concatenate()とnp.stack()

In [141]:
ndarray_even = np.arange(0, 18 ,2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [145]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [148]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [149]:
np.stack([ndarray_even, ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [154]:
stacked_array = _
stacked_array.shape

(2, 3, 3)

In [156]:
ndarray = np.random.randn(3, 4)
ndarray

array([[-0.39081754,  0.29815756, -1.1992002 , -0.58819046],
       [-0.49709792, -0.70837894, -1.04861911, -0.57562763],
       [ 0.09408346,  0.74747506, -0.09838155,  0.48182206]])

In [157]:
ndarray.shape

(3, 4)

In [158]:
np.transpose(ndarray)

array([[-0.39081754, -0.49709792,  0.09408346],
       [ 0.29815756, -0.70837894,  0.74747506],
       [-1.1992002 , -1.04861911, -0.09838155],
       [-0.58819046, -0.57562763,  0.48182206]])

In [159]:
ndarray.T

array([[-0.39081754, -0.49709792,  0.09408346],
       [ 0.29815756, -0.70837894,  0.74747506],
       [-1.1992002 , -1.04861911, -0.09838155],
       [-0.58819046, -0.57562763,  0.48182206]])

In [160]:
ndarray = np.random.randn(3, 4, 5)

In [162]:
ndarray.T

array([[[ 1.61512399e+00, -1.21947810e+00,  6.53556723e-01],
        [-1.60314205e+00,  4.10423802e-01,  3.81810775e-01],
        [ 1.46216679e+00, -6.83761998e-01,  1.13056269e+00],
        [-9.96186978e-01,  2.15810273e-01,  1.94526616e-03]],

       [[ 4.75314433e-01,  1.23074648e+00,  1.03791690e+00],
        [ 1.78377915e+00, -2.62688671e-02,  2.92051585e-01],
        [ 1.09933007e+00, -1.83467066e+00,  7.05651966e-01],
        [-1.24597297e-01,  5.72835657e-01,  2.48316556e+00]],

       [[-8.74554609e-01,  2.60090366e-01, -1.37927871e+00],
        [-1.45599782e+00,  1.26086952e-01, -4.34173745e-01],
        [ 5.61956348e-01,  5.17936969e-01,  1.46212671e+00],
        [ 1.12086113e+00,  1.09294992e-01, -5.51992625e-01]],

       [[-2.03965583e-01, -6.90708114e-02,  1.12797590e+00],
        [-1.13600415e-02,  5.64230863e-01, -8.38534139e-01],
        [ 8.60420348e-01,  1.98134961e-01,  8.62960854e-01],
        [-6.66491986e-01, -9.43678676e-01, -1.71405093e+00]],

       [[-1.1976

In [163]:
ndarrya = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [164]:
np.save('sample_ndarray', ndarray)

In [165]:
np.load('sample_ndarray.npy')

array([[[ 1.61512399e+00,  4.75314433e-01, -8.74554609e-01,
         -2.03965583e-01, -1.19763772e-01],
        [-1.60314205e+00,  1.78377915e+00, -1.45599782e+00,
         -1.13600415e-02,  1.26152864e+00],
        [ 1.46216679e+00,  1.09933007e+00,  5.61956348e-01,
          8.60420348e-01,  2.07008918e+00],
        [-9.96186978e-01, -1.24597297e-01,  1.12086113e+00,
         -6.66491986e-01,  7.86454981e-01]],

       [[-1.21947810e+00,  1.23074648e+00,  2.60090366e-01,
         -6.90708114e-02,  3.36125921e-01],
        [ 4.10423802e-01, -2.62688671e-02,  1.26086952e-01,
          5.64230863e-01, -2.15611707e-01],
        [-6.83761998e-01, -1.83467066e+00,  5.17936969e-01,
          1.98134961e-01, -1.19788842e-02],
        [ 2.15810273e-01,  5.72835657e-01,  1.09294992e-01,
         -9.43678676e-01,  1.56939886e-02]],

       [[ 6.53556723e-01,  1.03791690e+00, -1.37927871e+00,
          1.12797590e+00, -9.65028427e-01],
        [ 3.81810775e-01,  2.92051585e-01, -4.34173745e-01,
